//! Generate the committed C header (cbindgen 0.29) and the committed C# P/Invoke
//! bindings (csbindgen) from the crate's `extern "C"` surface.
//!
//! The header at `include/skopli.h` (crate-relative) is committed and CI
//! checks that regenerating it is a zero-diff (append-only) operation. To keep
//! ordinary `cargo build` fast and side-effect-free, generation only runs when
//! `SKOPLI_GEN_HEADER=1` is set (the header-check script sets it, and it can
//! be set manually to refresh the header). A normal build just re-declares the
//! source dependency so a stale committed header is never silently trusted.
//!
//! Likewise, the C# `NativeMethods.g.cs` at
//! `../../sdks/csharp/Skopli/Native/NativeMethods.g.cs` is regenerated by
//! csbindgen only when `SKOPLI_GEN_CSHARP=1` is set (the C#-bindings check
//! script sets it), so the committed P/Invoke surface stays a zero-diff of the
//! Rust `extern "C"` symbols without slowing normal builds.

use std::env;
use std::path::{Path, PathBuf};

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    println!("cargo:rerun-if-changed=src/lib.rs");
    println!("cargo:rerun-if-changed=src/abi.rs");
    println!("cargo:rerun-if-changed=cbindgen.toml");
    println!("cargo:rerun-if-env-changed=SKOPLI_GEN_HEADER");
    println!("cargo:rerun-if-env-changed=SKOPLI_GEN_CSHARP");

    if env::var("SKOPLI_GEN_HEADER").as_deref() == Ok("1") {
        gen_header(&crate_dir);
    }

    if env::var("SKOPLI_GEN_CSHARP").as_deref() == Ok("1") {
        gen_csharp(&crate_dir);
    }
}

/// Regenerate the committed C header via cbindgen.
fn gen_header(crate_dir: &Path) {
    let config =
        cbindgen::Config::from_file(crate_dir.join("cbindgen.toml")).expect("read cbindgen.toml");

    let bindings = cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_config(config)
        .generate()
        .expect("generate cbindgen bindings");

    let out = crate_dir.join("include").join("skopli.h");
    std::fs::create_dir_all(out.parent().unwrap()).expect("create include dir");
    bindings.write_to_file(&out);
}

/// Regenerate the committed C# P/Invoke bindings via csbindgen. Scans the crate's
/// `extern "C"` surface (`lib.rs` + `abi.rs`) and emits a single
/// `NativeMethods.g.cs` under the C# SDK, matching the DllImport name/namespace
/// the hand-written facade consumes.
fn gen_csharp(crate_dir: &Path) {
    let out = crate_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("repo root")
        .join("sdks")
        .join("csharp")
        .join("Skopli")
        .join("Native")
        .join("NativeMethods.g.cs");
    std::fs::create_dir_all(out.parent().unwrap()).expect("create Native dir");

    csbindgen::Builder::default()
        .input_extern_file(crate_dir.join("src").join("lib.rs"))
        .input_extern_file(crate_dir.join("src").join("abi.rs"))
        .csharp_dll_name("skopli")
        .csharp_namespace("Skopli.Native")
        .csharp_class_name("NativeMethods")
        .csharp_class_accessibility("internal")
        .generate_csharp_file(&out)
        .expect("generate csbindgen C# bindings");
}
