// Generated by jextract

package com.skopli.ffi;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

public class Skopli {

    Skopli() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();
    static final boolean TRACE_DOWNCALLS = Boolean.getBoolean("jextract.trace.downcalls");

    static void traceDowncall(String name, Object... args) {
         String traceArgs = Arrays.stream(args)
                       .map(Object::toString)
                       .collect(Collectors.joining(", "));
         System.out.printf("%s(%s)\n", name, traceArgs);
    }

    static MemorySegment findOrThrow(String symbol) {
        return SYMBOL_LOOKUP.find(symbol)
            .orElseThrow(() -> new UnsatisfiedLinkError("unresolved symbol: " + symbol));
    }

    static MethodHandle upcallHandle(Class<?> fi, String name, FunctionDescriptor fdesc) {
        try {
            return MethodHandles.lookup().findVirtual(fi, name, fdesc.toMethodType());
        } catch (ReflectiveOperationException ex) {
            throw new AssertionError(ex);
        }
    }

    static MemoryLayout align(MemoryLayout layout, long align) {
        return switch (layout) {
            case PaddingLayout p -> p;
            case ValueLayout v -> v.withByteAlignment(align);
            case GroupLayout g -> {
                MemoryLayout[] alignedMembers = g.memberLayouts().stream()
                        .map(m -> align(m, align)).toArray(MemoryLayout[]::new);
                yield g instanceof StructLayout ?
                        MemoryLayout.structLayout(alignedMembers) : MemoryLayout.unionLayout(alignedMembers);
            }
            case SequenceLayout s -> MemoryLayout.sequenceLayout(s.elementCount(), align(s.elementLayout(), align));
        };
    }

    static final SymbolLookup SYMBOL_LOOKUP = SymbolLookup.loaderLookup()
            .or(Linker.nativeLinker().defaultLookup());

    public static final ValueLayout.OfBoolean C_BOOL = ValueLayout.JAVA_BOOLEAN;
    public static final ValueLayout.OfByte C_CHAR = ValueLayout.JAVA_BYTE;
    public static final ValueLayout.OfShort C_SHORT = ValueLayout.JAVA_SHORT;
    public static final ValueLayout.OfInt C_INT = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfLong C_LONG_LONG = ValueLayout.JAVA_LONG;
    public static final ValueLayout.OfFloat C_FLOAT = ValueLayout.JAVA_FLOAT;
    public static final ValueLayout.OfDouble C_DOUBLE = ValueLayout.JAVA_DOUBLE;
    public static final AddressLayout C_POINTER = ValueLayout.ADDRESS
            .withTargetLayout(MemoryLayout.sequenceLayout(java.lang.Long.MAX_VALUE, JAVA_BYTE));
    public static final ValueLayout.OfInt C_LONG = ValueLayout.JAVA_INT;
    public static final ValueLayout.OfDouble C_LONG_DOUBLE = ValueLayout.JAVA_DOUBLE;
    /**
     * {@snippet lang=c :
     * typedef int32_t AgStatus
     * }
     */
    public static final OfInt AgStatus = Skopli.C_INT;

    private static class ag_abi_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT    );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_abi_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t ag_abi_version()
     * }
     */
    public static FunctionDescriptor ag_abi_version$descriptor() {
        return ag_abi_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t ag_abi_version()
     * }
     */
    public static MethodHandle ag_abi_version$handle() {
        return ag_abi_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t ag_abi_version()
     * }
     */
    public static MemorySegment ag_abi_version$address() {
        return ag_abi_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t ag_abi_version()
     * }
     */
    public static int ag_abi_version() {
        var mh$ = ag_abi_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_abi_version");
            }
            return (int)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_schema_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT    );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_schema_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * uint32_t ag_schema_version()
     * }
     */
    public static FunctionDescriptor ag_schema_version$descriptor() {
        return ag_schema_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * uint32_t ag_schema_version()
     * }
     */
    public static MethodHandle ag_schema_version$handle() {
        return ag_schema_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * uint32_t ag_schema_version()
     * }
     */
    public static MemorySegment ag_schema_version$address() {
        return ag_schema_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * uint32_t ag_schema_version()
     * }
     */
    public static int ag_schema_version() {
        var mh$ = ag_schema_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_schema_version");
            }
            return (int)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_version {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_POINTER    );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_version");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * const char *ag_version()
     * }
     */
    public static FunctionDescriptor ag_version$descriptor() {
        return ag_version.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * const char *ag_version()
     * }
     */
    public static MethodHandle ag_version$handle() {
        return ag_version.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * const char *ag_version()
     * }
     */
    public static MemorySegment ag_version$address() {
        return ag_version.ADDR;
    }

    /**
     * {@snippet lang=c :
     * const char *ag_version()
     * }
     */
    public static MemorySegment ag_version() {
        var mh$ = ag_version.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_version");
            }
            return (MemorySegment)mh$.invokeExact();
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_detect_harnesses {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_detect_harnesses");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_detect_harnesses(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_detect_harnesses$descriptor() {
        return ag_detect_harnesses.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_detect_harnesses(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MethodHandle ag_detect_harnesses$handle() {
        return ag_detect_harnesses.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_detect_harnesses(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MemorySegment ag_detect_harnesses$address() {
        return ag_detect_harnesses.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_detect_harnesses(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static int ag_detect_harnesses(MemorySegment opts_json, long opts_len, MemorySegment out) {
        var mh$ = ag_detect_harnesses.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_detect_harnesses", opts_json, opts_len, out);
            }
            return (int)mh$.invokeExact(opts_json, opts_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_read_usage {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_read_usage");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_read_usage(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_read_usage$descriptor() {
        return ag_read_usage.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_read_usage(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MethodHandle ag_read_usage$handle() {
        return ag_read_usage.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_read_usage(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MemorySegment ag_read_usage$address() {
        return ag_read_usage.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_read_usage(const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static int ag_read_usage(MemorySegment opts_json, long opts_len, MemorySegment out) {
        var mh$ = ag_read_usage.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_read_usage", opts_json, opts_len, out);
            }
            return (int)mh$.invokeExact(opts_json, opts_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_rollup {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_rollup");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_rollup(const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_rollup$descriptor() {
        return ag_rollup.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_rollup(const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MethodHandle ag_rollup$handle() {
        return ag_rollup.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_rollup(const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MemorySegment ag_rollup$address() {
        return ag_rollup.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_rollup(const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static int ag_rollup(MemorySegment events_json, long events_len, MemorySegment opts_json, long opts_len, MemorySegment out) {
        var mh$ = ag_rollup.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_rollup", events_json, events_len, opts_json, opts_len, out);
            }
            return (int)mh$.invokeExact(events_json, events_len, opts_json, opts_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_cost_usd {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_cost_usd");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_cost_usd(const char *tokens_json, uintptr_t tokens_len, const char *price_json, uintptr_t price_len, double *out)
     * }
     */
    public static FunctionDescriptor ag_cost_usd$descriptor() {
        return ag_cost_usd.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_cost_usd(const char *tokens_json, uintptr_t tokens_len, const char *price_json, uintptr_t price_len, double *out)
     * }
     */
    public static MethodHandle ag_cost_usd$handle() {
        return ag_cost_usd.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_cost_usd(const char *tokens_json, uintptr_t tokens_len, const char *price_json, uintptr_t price_len, double *out)
     * }
     */
    public static MemorySegment ag_cost_usd$address() {
        return ag_cost_usd.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_cost_usd(const char *tokens_json, uintptr_t tokens_len, const char *price_json, uintptr_t price_len, double *out)
     * }
     */
    public static int ag_cost_usd(MemorySegment tokens_json, long tokens_len, MemorySegment price_json, long price_len, MemorySegment out) {
        var mh$ = ag_cost_usd.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_cost_usd", tokens_json, tokens_len, price_json, price_len, out);
            }
            return (int)mh$.invokeExact(tokens_json, tokens_len, price_json, price_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_default_cache_dir {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_default_cache_dir");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_default_cache_dir(char **out)
     * }
     */
    public static FunctionDescriptor ag_default_cache_dir$descriptor() {
        return ag_default_cache_dir.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_default_cache_dir(char **out)
     * }
     */
    public static MethodHandle ag_default_cache_dir$handle() {
        return ag_default_cache_dir.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_default_cache_dir(char **out)
     * }
     */
    public static MemorySegment ag_default_cache_dir$address() {
        return ag_default_cache_dir.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_default_cache_dir(char **out)
     * }
     */
    public static int ag_default_cache_dir(MemorySegment out) {
        var mh$ = ag_default_cache_dir.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_default_cache_dir", out);
            }
            return (int)mh$.invokeExact(out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_pricing_new {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_pricing_new");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_new(const char *opts_json, uintptr_t opts_len, AgPricing **out)
     * }
     */
    public static FunctionDescriptor ag_pricing_new$descriptor() {
        return ag_pricing_new.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_new(const char *opts_json, uintptr_t opts_len, AgPricing **out)
     * }
     */
    public static MethodHandle ag_pricing_new$handle() {
        return ag_pricing_new.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_new(const char *opts_json, uintptr_t opts_len, AgPricing **out)
     * }
     */
    public static MemorySegment ag_pricing_new$address() {
        return ag_pricing_new.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_pricing_new(const char *opts_json, uintptr_t opts_len, AgPricing **out)
     * }
     */
    public static int ag_pricing_new(MemorySegment opts_json, long opts_len, MemorySegment out) {
        var mh$ = ag_pricing_new.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_pricing_new", opts_json, opts_len, out);
            }
            return (int)mh$.invokeExact(opts_json, opts_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_pricing_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_pricing_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void ag_pricing_free(AgPricing *pricing)
     * }
     */
    public static FunctionDescriptor ag_pricing_free$descriptor() {
        return ag_pricing_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void ag_pricing_free(AgPricing *pricing)
     * }
     */
    public static MethodHandle ag_pricing_free$handle() {
        return ag_pricing_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void ag_pricing_free(AgPricing *pricing)
     * }
     */
    public static MemorySegment ag_pricing_free$address() {
        return ag_pricing_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void ag_pricing_free(AgPricing *pricing)
     * }
     */
    public static void ag_pricing_free(MemorySegment pricing) {
        var mh$ = ag_pricing_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_pricing_free", pricing);
            }
            mh$.invokeExact(pricing);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_pricing_price_events {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_pricing_price_events");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_events(const AgPricing *pricing, const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_pricing_price_events$descriptor() {
        return ag_pricing_price_events.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_events(const AgPricing *pricing, const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MethodHandle ag_pricing_price_events$handle() {
        return ag_pricing_price_events.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_events(const AgPricing *pricing, const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static MemorySegment ag_pricing_price_events$address() {
        return ag_pricing_price_events.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_events(const AgPricing *pricing, const char *events_json, uintptr_t events_len, const char *opts_json, uintptr_t opts_len, AgBuf *out)
     * }
     */
    public static int ag_pricing_price_events(MemorySegment pricing, MemorySegment events_json, long events_len, MemorySegment opts_json, long opts_len, MemorySegment out) {
        var mh$ = ag_pricing_price_events.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_pricing_price_events", pricing, events_json, events_len, opts_json, opts_len, out);
            }
            return (int)mh$.invokeExact(pricing, events_json, events_len, opts_json, opts_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_pricing_lookup_model {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_pricing_lookup_model");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_lookup_model(const AgPricing *pricing, const char *model, uintptr_t model_len, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_pricing_lookup_model$descriptor() {
        return ag_pricing_lookup_model.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_lookup_model(const AgPricing *pricing, const char *model, uintptr_t model_len, AgBuf *out)
     * }
     */
    public static MethodHandle ag_pricing_lookup_model$handle() {
        return ag_pricing_lookup_model.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_lookup_model(const AgPricing *pricing, const char *model, uintptr_t model_len, AgBuf *out)
     * }
     */
    public static MemorySegment ag_pricing_lookup_model$address() {
        return ag_pricing_lookup_model.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_pricing_lookup_model(const AgPricing *pricing, const char *model, uintptr_t model_len, AgBuf *out)
     * }
     */
    public static int ag_pricing_lookup_model(MemorySegment pricing, MemorySegment model, long model_len, MemorySegment out) {
        var mh$ = ag_pricing_lookup_model.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_pricing_lookup_model", pricing, model, model_len, out);
            }
            return (int)mh$.invokeExact(pricing, model, model_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_pricing_price_rollups {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_POINTER,
            Skopli.C_LONG_LONG,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_pricing_price_rollups");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_rollups(const AgPricing *pricing, const char *rollups_json, uintptr_t rollups_len, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_pricing_price_rollups$descriptor() {
        return ag_pricing_price_rollups.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_rollups(const AgPricing *pricing, const char *rollups_json, uintptr_t rollups_len, AgBuf *out)
     * }
     */
    public static MethodHandle ag_pricing_price_rollups$handle() {
        return ag_pricing_price_rollups.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_rollups(const AgPricing *pricing, const char *rollups_json, uintptr_t rollups_len, AgBuf *out)
     * }
     */
    public static MemorySegment ag_pricing_price_rollups$address() {
        return ag_pricing_price_rollups.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_pricing_price_rollups(const AgPricing *pricing, const char *rollups_json, uintptr_t rollups_len, AgBuf *out)
     * }
     */
    public static int ag_pricing_price_rollups(MemorySegment pricing, MemorySegment rollups_json, long rollups_len, MemorySegment out) {
        var mh$ = ag_pricing_price_rollups.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_pricing_price_rollups", pricing, rollups_json, rollups_len, out);
            }
            return (int)mh$.invokeExact(pricing, rollups_json, rollups_len, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_pricing_catalog_info {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_pricing_catalog_info");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_catalog_info(const AgPricing *pricing, AgBuf *out)
     * }
     */
    public static FunctionDescriptor ag_pricing_catalog_info$descriptor() {
        return ag_pricing_catalog_info.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_catalog_info(const AgPricing *pricing, AgBuf *out)
     * }
     */
    public static MethodHandle ag_pricing_catalog_info$handle() {
        return ag_pricing_catalog_info.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_pricing_catalog_info(const AgPricing *pricing, AgBuf *out)
     * }
     */
    public static MemorySegment ag_pricing_catalog_info$address() {
        return ag_pricing_catalog_info.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_pricing_catalog_info(const AgPricing *pricing, AgBuf *out)
     * }
     */
    public static int ag_pricing_catalog_info(MemorySegment pricing, MemorySegment out) {
        var mh$ = ag_pricing_catalog_info.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_pricing_catalog_info", pricing, out);
            }
            return (int)mh$.invokeExact(pricing, out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_buf_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            AgBuf.layout()
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_buf_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void ag_buf_free(AgBuf buf)
     * }
     */
    public static FunctionDescriptor ag_buf_free$descriptor() {
        return ag_buf_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void ag_buf_free(AgBuf buf)
     * }
     */
    public static MethodHandle ag_buf_free$handle() {
        return ag_buf_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void ag_buf_free(AgBuf buf)
     * }
     */
    public static MemorySegment ag_buf_free$address() {
        return ag_buf_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void ag_buf_free(AgBuf buf)
     * }
     */
    public static void ag_buf_free(MemorySegment buf) {
        var mh$ = ag_buf_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_buf_free", buf);
            }
            mh$.invokeExact(buf);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_string_free {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_string_free");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void ag_string_free(char *s)
     * }
     */
    public static FunctionDescriptor ag_string_free$descriptor() {
        return ag_string_free.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void ag_string_free(char *s)
     * }
     */
    public static MethodHandle ag_string_free$handle() {
        return ag_string_free.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void ag_string_free(char *s)
     * }
     */
    public static MemorySegment ag_string_free$address() {
        return ag_string_free.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void ag_string_free(char *s)
     * }
     */
    public static void ag_string_free(MemorySegment s) {
        var mh$ = ag_string_free.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_string_free", s);
            }
            mh$.invokeExact(s);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class ag_last_error_message {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Skopli.C_INT,
            Skopli.C_POINTER
        );

        public static final MemorySegment ADDR = Skopli.findOrThrow("ag_last_error_message");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * AgStatus ag_last_error_message(char **out)
     * }
     */
    public static FunctionDescriptor ag_last_error_message$descriptor() {
        return ag_last_error_message.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * AgStatus ag_last_error_message(char **out)
     * }
     */
    public static MethodHandle ag_last_error_message$handle() {
        return ag_last_error_message.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * AgStatus ag_last_error_message(char **out)
     * }
     */
    public static MemorySegment ag_last_error_message$address() {
        return ag_last_error_message.ADDR;
    }

    /**
     * {@snippet lang=c :
     * AgStatus ag_last_error_message(char **out)
     * }
     */
    public static int ag_last_error_message(MemorySegment out) {
        var mh$ = ag_last_error_message.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("ag_last_error_message", out);
            }
            return (int)mh$.invokeExact(out);
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}

