// Gradle build for the skopli Java SDK (FFM + jextract, JDK 22+).
//
// NOTE: when the build host has no Gradle/Maven installed, the smoke test is
// built and run with plain javac/java (see scripts/smoke.sh and the README).
// This config is the SHIPPED, canonical build a real consumer would use; it is
// intentionally dependency-free (the facade uses only the JDK).
//
// The jextract-generated bindings under src/main/java/com/skopli/ffi/ are
// COMMITTED (regenerated by scripts/regen-bindings.sh, zero-diff-checked by
// scripts/check-bindings.sh), so a plain build needs no jextract on PATH.

plugins {
    `java-library`
}

group = "com.skopli"
version = "0.1.0"

java {
    // FFM is stable since JDK 22 (the baseline); JDK 25 is the dev toolchain.
    toolchain {
        languageVersion = JavaLanguageVersion.of(22)
    }
    withSourcesJar()
}

repositories {
    mavenCentral()
}

dependencies {
    // No runtime deps: the facade is pure JDK (FFM + a hand-rolled JSON codec).
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// The absolute path to the built skopli cdylib, defaulting to the workspace
// release target. Override with -Pskopli.library.path=... .
val nativeLibraryPath: String = (project.findProperty("skopli.library.path") as String?)
    ?: rootProject.layout.projectDirectory
        .dir("../../target/release")
        .file(
            when {
                org.gradle.internal.os.OperatingSystem.current().isWindows -> "skopli.dll"
                org.gradle.internal.os.OperatingSystem.current().isMacOsX -> "libskopli.dylib"
                else -> "libskopli.so"
            }
        ).asFile.absolutePath

tasks.withType<JavaCompile>().configureEach {
    // FFM downcalls compile fine; silence the generated-binding restricted warnings.
    options.compilerArgs.addAll(listOf("-Xlint:all,-restricted"))
}

tasks.test {
    useJUnitPlatform()
    // Allow FFM native access and point the loader at the cdylib.
    jvmArgs(
        "--enable-native-access=ALL-UNNAMED",
        "-Dskopli.library.path=$nativeLibraryPath",
    )
}

// Convenience: regenerate the committed jextract bindings (needs jextract on
// PATH via the JEXTRACT env var). Not part of `build` - the bindings are
// committed - but available for a deliberate refresh after a C ABI change.
tasks.register<Exec>("regenBindings") {
    workingDir = projectDir
    commandLine("bash", "scripts/regen-bindings.sh")
}

tasks.register<Exec>("checkBindings") {
    workingDir = projectDir
    commandLine("bash", "scripts/check-bindings.sh")
}
