[package]
name = "skopli-wire"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
homepage.workspace = true
documentation.workspace = true
repository.workspace = true
publish = false

[dependencies]
skopli-core = { path = "../skopli-core" }
serde_json = { workspace = true }
jiff = { workspace = true }
