"""Type stubs for the native ``_skopli`` extension module.

The native surface is a JSON string-in/string-out boundary; the typed public API
lives in the pure-Python facade over it. These stubs let type-checkers verify the
facade's calls into the extension.
"""

__version__: str

class SkopliError(Exception):
    kind: str

def default_cache_dir() -> str: ...
def detect_harnesses(options_json: str) -> str: ...
def read_usage(options_json: str) -> str: ...
def rollup(events_json: str, options_json: str) -> str: ...
def cost_usd(tokens_json: str, price_json: str) -> float: ...

class Pricing:
    def __init__(self, options_json: str) -> None: ...
    def catalogs(self) -> str: ...
    def lookup_model(self, model: str) -> str: ...
    def price_rollups(self, rollups_json: str) -> str: ...
    def price_events(self, events_json: str, options_json: str) -> str: ...
